wandb_version: 1

workdir:
  desc: null
  value: ./experiments/Replica
run_name:
  desc: null
  value: room0_0
seed:
  desc: null
  value: 0
primary_device:
  desc: null
  value: cuda:0
map_every:
  desc: null
  value: 1
keyframe_every:
  desc: null
  value: 5
mapping_window_size:
  desc: null
  value: 24
report_global_progress_every:
  desc: null
  value: 500
eval_every:
  desc: null
  value: 5
scene_radius_depth_ratio:
  desc: null
  value: 3
mean_sq_dist_method:
  desc: null
  value: projective
report_iter_progress:
  desc: null
  value: false
load_checkpoint:
  desc: null
  value: false
checkpoint_time_idx:
  desc: null
  value: 0
save_checkpoints:
  desc: null
  value: false
checkpoint_interval:
  desc: null
  value: 100
use_wandb:
  desc: null
  value: true
wandb:
  desc: null
  value:
    entity: theairlab
    project: SplaTAM
    group: Replica
    name: room0_0
    save_qual: false
    eval_save_qual: true
data:
  desc: null
  value:
    basedir: ./data/Replica
    gradslam_data_cfg: ./configs/data/replica.yaml
    sequence: room0
    desired_image_height: 680
    desired_image_width: 1200
    start: 0
    end: -1
    stride: 1
    num_frames: -1
tracking:
  desc: null
  value:
    use_gt_poses: false
    forward_prop: true
    num_iters: 40
    use_sil_for_loss: true
    sil_thres: 0.99
    use_l1: true
    ignore_outlier_depth_loss: false
    loss_weights:
      im: 0.5
      depth: 1.0
    lrs:
      means3D: 0.0
      rgb_colors: 0.0
      unnorm_rotations: 0.0
      logit_opacities: 0.0
      log_scales: 0.0
      cam_unnorm_rots: 0.0004
      cam_trans: 0.002
    use_depth_loss_thres: false
    depth_loss_thres: 100000
    visualize_tracking_loss: false
mapping:
  desc: null
  value:
    num_iters: 60
    add_new_gaussians: true
    sil_thres: 0.5
    use_l1: true
    use_sil_for_loss: false
    ignore_outlier_depth_loss: false
    loss_weights:
      im: 0.5
      depth: 1.0
    lrs:
      means3D: 0.0001
      rgb_colors: 0.0025
      unnorm_rotations: 0.001
      logit_opacities: 0.05
      log_scales: 0.001
      cam_unnorm_rots: 0.0
      cam_trans: 0.0
    prune_gaussians: true
    pruning_dict:
      start_after: 0
      remove_big_after: 0
      stop_after: 20
      prune_every: 20
      removal_opacity_threshold: 0.005
      final_removal_opacity_threshold: 0.005
      reset_opacities: false
      reset_opacities_every: 500
    use_gaussian_splatting_densification: false
    densify_dict:
      start_after: 500
      remove_big_after: 3000
      stop_after: 5000
      densify_every: 100
      grad_thresh: 0.0002
      num_to_split_into: 2
      removal_opacity_threshold: 0.005
      final_removal_opacity_threshold: 0.005
      reset_opacities_every: 3000
viz:
  desc: null
  value:
    render_mode: color
    offset_first_viz_cam: true
    show_sil: false
    visualize_cams: true
    viz_w: 600
    viz_h: 340
    viz_near: 0.01
    viz_far: 100.0
    view_scale: 2
    viz_fps: 5
    enter_interactive_post_online: true
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702542473.961096
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      - 79
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
